# Generated by Django 2.2.4 on 2020-03-25 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='text',
            new_name='todo',
        ),
    ]
